[package]
name = "window-shadows-v2"
description = "Add native shadows to your windows for tauri v2."
authors = [ "CeerDecy" ]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/nautilus-ops/window-shadow-v2"
keywords = [ "shadows", "windowing", "gui" ]
categories = [ "gui" ]

[dependencies]
tauri = { version = "2", features = ["unstable"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_UI_Controls"] }
